### ISSUE TITLE
Organization了解一下

### ISSUE THREAD

**Issue by Bambusaceae** [code004Accepted/GC-Server-dev#7]
如题

<https://github.com/organizations/new>

**Comment by code004Accepted** [comment]
> 如题
> 
> https://github.com/organizations/new

已经有一个organization 了qwq  手机上不方便回复link qwq

**Comment by code004Accepted** [comment]
> 如题
> 
> https://github.com/organizations/new

好的，找到了

https://github.com/gcserver

**Comment by chuang-zhi** [comment]
😏
